/*
 * This file is generated by jOOQ.
 */
package rosemary_and_thyme.backend.models.`public`


import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl

import rosemary_and_thyme.backend.models.DefaultCatalog


/**
 * standard public schema
 */
@Suppress("warnings")
open class Public : SchemaImpl(DSL.name("public"), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("standard public schema")) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.hero_images</code>.
     */
    val HERO_IMAGES: rosemary_and_thyme.backend.models.`public`.tables.HeroImages get() = rosemary_and_thyme.backend.models.`public`.tables.HeroImages.HERO_IMAGES

    /**
     * The table <code>public.ingredients</code>.
     */
    val INGREDIENTS: rosemary_and_thyme.backend.models.`public`.tables.Ingredients get() = rosemary_and_thyme.backend.models.`public`.tables.Ingredients.INGREDIENTS

    /**
     * The table <code>public.instruction_images</code>.
     */
    val INSTRUCTION_IMAGES: rosemary_and_thyme.backend.models.`public`.tables.InstructionImages get() = rosemary_and_thyme.backend.models.`public`.tables.InstructionImages.INSTRUCTION_IMAGES

    /**
     * The table <code>public.instructions</code>.
     */
    val INSTRUCTIONS: rosemary_and_thyme.backend.models.`public`.tables.Instructions get() = rosemary_and_thyme.backend.models.`public`.tables.Instructions.INSTRUCTIONS

    /**
     * The table <code>public.recipes</code>.
     */
    val RECIPES: rosemary_and_thyme.backend.models.`public`.tables.Recipes get() = rosemary_and_thyme.backend.models.`public`.tables.Recipes.RECIPES

    /**
     * The table <code>public.users</code>.
     */
    val USERS: rosemary_and_thyme.backend.models.`public`.tables.Users get() = rosemary_and_thyme.backend.models.`public`.tables.Users.USERS

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        rosemary_and_thyme.backend.models.`public`.tables.HeroImages.HERO_IMAGES,
        rosemary_and_thyme.backend.models.`public`.tables.Ingredients.INGREDIENTS,
        rosemary_and_thyme.backend.models.`public`.tables.InstructionImages.INSTRUCTION_IMAGES,
        rosemary_and_thyme.backend.models.`public`.tables.Instructions.INSTRUCTIONS,
        rosemary_and_thyme.backend.models.`public`.tables.Recipes.RECIPES,
        rosemary_and_thyme.backend.models.`public`.tables.Users.USERS
    )
}
