@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package rosemary_and_thyme.backend.models.`public`.keys


import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.QOM.ForeignKeyRule



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val HERO_IMAGES_PKEY: UniqueKey<rosemary_and_thyme.backend.models.`public`.tables.records.HeroImagesRecord> = Internal.createUniqueKey(rosemary_and_thyme.backend.models.`public`.tables.HeroImages.HERO_IMAGES, DSL.name("hero_images_pkey"), arrayOf(rosemary_and_thyme.backend.models.`public`.tables.HeroImages.HERO_IMAGES.ID), true)
val HERO_IMAGES_RECIPE_ID_INDEX_KEY: UniqueKey<rosemary_and_thyme.backend.models.`public`.tables.records.HeroImagesRecord> = Internal.createUniqueKey(rosemary_and_thyme.backend.models.`public`.tables.HeroImages.HERO_IMAGES, DSL.name("hero_images_recipe_id_index_key"), arrayOf(rosemary_and_thyme.backend.models.`public`.tables.HeroImages.HERO_IMAGES.RECIPE_ID, rosemary_and_thyme.backend.models.`public`.tables.HeroImages.HERO_IMAGES.INDEX), true)
val INGREDIENTS_PKEY: UniqueKey<rosemary_and_thyme.backend.models.`public`.tables.records.IngredientsRecord> = Internal.createUniqueKey(rosemary_and_thyme.backend.models.`public`.tables.Ingredients.INGREDIENTS, DSL.name("ingredients_pkey"), arrayOf(rosemary_and_thyme.backend.models.`public`.tables.Ingredients.INGREDIENTS.ID), true)
val INGREDIENTS_RECIPE_ID_INDEX_KEY: UniqueKey<rosemary_and_thyme.backend.models.`public`.tables.records.IngredientsRecord> = Internal.createUniqueKey(rosemary_and_thyme.backend.models.`public`.tables.Ingredients.INGREDIENTS, DSL.name("ingredients_recipe_id_index_key"), arrayOf(rosemary_and_thyme.backend.models.`public`.tables.Ingredients.INGREDIENTS.RECIPE_ID, rosemary_and_thyme.backend.models.`public`.tables.Ingredients.INGREDIENTS.INDEX), true)
val INSTRUCTION_IMAGES_INSTRUCTION_ID_INDEX_KEY: UniqueKey<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionImagesRecord> = Internal.createUniqueKey(rosemary_and_thyme.backend.models.`public`.tables.InstructionImages.INSTRUCTION_IMAGES, DSL.name("instruction_images_instruction_id_index_key"), arrayOf(rosemary_and_thyme.backend.models.`public`.tables.InstructionImages.INSTRUCTION_IMAGES.INSTRUCTION_ID, rosemary_and_thyme.backend.models.`public`.tables.InstructionImages.INSTRUCTION_IMAGES.INDEX), true)
val INSTRUCTION_IMAGES_PKEY: UniqueKey<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionImagesRecord> = Internal.createUniqueKey(rosemary_and_thyme.backend.models.`public`.tables.InstructionImages.INSTRUCTION_IMAGES, DSL.name("instruction_images_pkey"), arrayOf(rosemary_and_thyme.backend.models.`public`.tables.InstructionImages.INSTRUCTION_IMAGES.ID), true)
val INSTRUCTIONS_PKEY: UniqueKey<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord> = Internal.createUniqueKey(rosemary_and_thyme.backend.models.`public`.tables.Instructions.INSTRUCTIONS, DSL.name("instructions_pkey"), arrayOf(rosemary_and_thyme.backend.models.`public`.tables.Instructions.INSTRUCTIONS.ID), true)
val INSTRUCTIONS_RECIPE_ID_INDEX_KEY: UniqueKey<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord> = Internal.createUniqueKey(rosemary_and_thyme.backend.models.`public`.tables.Instructions.INSTRUCTIONS, DSL.name("instructions_recipe_id_index_key"), arrayOf(rosemary_and_thyme.backend.models.`public`.tables.Instructions.INSTRUCTIONS.RECIPE_ID, rosemary_and_thyme.backend.models.`public`.tables.Instructions.INSTRUCTIONS.INDEX), true)
val RECIPES_PKEY: UniqueKey<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord> = Internal.createUniqueKey(rosemary_and_thyme.backend.models.`public`.tables.Recipes.RECIPES, DSL.name("recipes_pkey"), arrayOf(rosemary_and_thyme.backend.models.`public`.tables.Recipes.RECIPES.ID), true)
val USERS_PKEY: UniqueKey<rosemary_and_thyme.backend.models.`public`.tables.records.UsersRecord> = Internal.createUniqueKey(rosemary_and_thyme.backend.models.`public`.tables.Users.USERS, DSL.name("users_pkey"), arrayOf(rosemary_and_thyme.backend.models.`public`.tables.Users.USERS.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val HERO_IMAGES__HERO_IMAGES_RECIPE_ID_FKEY: ForeignKey<rosemary_and_thyme.backend.models.`public`.tables.records.HeroImagesRecord, rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord> = Internal.createForeignKey(rosemary_and_thyme.backend.models.`public`.tables.HeroImages.HERO_IMAGES, DSL.name("hero_images_recipe_id_fkey"), arrayOf(rosemary_and_thyme.backend.models.`public`.tables.HeroImages.HERO_IMAGES.RECIPE_ID), rosemary_and_thyme.backend.models.`public`.keys.RECIPES_PKEY, arrayOf(rosemary_and_thyme.backend.models.`public`.tables.Recipes.RECIPES.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val INGREDIENTS__INGREDIENTS_RECIPE_ID_FKEY: ForeignKey<rosemary_and_thyme.backend.models.`public`.tables.records.IngredientsRecord, rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord> = Internal.createForeignKey(rosemary_and_thyme.backend.models.`public`.tables.Ingredients.INGREDIENTS, DSL.name("ingredients_recipe_id_fkey"), arrayOf(rosemary_and_thyme.backend.models.`public`.tables.Ingredients.INGREDIENTS.RECIPE_ID), rosemary_and_thyme.backend.models.`public`.keys.RECIPES_PKEY, arrayOf(rosemary_and_thyme.backend.models.`public`.tables.Recipes.RECIPES.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val INSTRUCTION_IMAGES__INSTRUCTION_IMAGES_INSTRUCTION_ID_FKEY: ForeignKey<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionImagesRecord, rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord> = Internal.createForeignKey(rosemary_and_thyme.backend.models.`public`.tables.InstructionImages.INSTRUCTION_IMAGES, DSL.name("instruction_images_instruction_id_fkey"), arrayOf(rosemary_and_thyme.backend.models.`public`.tables.InstructionImages.INSTRUCTION_IMAGES.INSTRUCTION_ID), rosemary_and_thyme.backend.models.`public`.keys.INSTRUCTIONS_PKEY, arrayOf(rosemary_and_thyme.backend.models.`public`.tables.Instructions.INSTRUCTIONS.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
val INSTRUCTIONS__INSTRUCTIONS_RECIPE_ID_FKEY: ForeignKey<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord, rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord> = Internal.createForeignKey(rosemary_and_thyme.backend.models.`public`.tables.Instructions.INSTRUCTIONS, DSL.name("instructions_recipe_id_fkey"), arrayOf(rosemary_and_thyme.backend.models.`public`.tables.Instructions.INSTRUCTIONS.RECIPE_ID), rosemary_and_thyme.backend.models.`public`.keys.RECIPES_PKEY, arrayOf(rosemary_and_thyme.backend.models.`public`.tables.Recipes.RECIPES.ID), true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION)
