@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package rosemary_and_thyme.backend.models.users.tables.references


import rosemary_and_thyme.backend.models.users.tables.Users



/**
 * The table <code>users.users</code>.
 */
val USERS_: Users = Users.USERS_
