/*
 * This file is generated by jOOQ.
 */
package rosemary_and_thyme.backend.models.users


import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl

import rosemary_and_thyme.backend.models.DefaultCatalog


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Users : SchemaImpl(DSL.name("users"), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("")) {
    companion object {

        /**
         * The reference instance of <code>users</code>
         */
        val USERS: Users = Users()
    }

    /**
     * The table <code>users.users</code>.
     */
    val USERS_ : rosemary_and_thyme.backend.models.users.tables.Users get() = rosemary_and_thyme.backend.models.users.tables.Users.USERS_

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        rosemary_and_thyme.backend.models.users.tables.Users.USERS_
    )
}
