/*
 * This file is generated by jOOQ.
 */
package rosemary_and_thyme.backend.models.users.tables.records


import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl

import rosemary_and_thyme.backend.models.users.tables.Users


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UsersRecord private constructor() : UpdatableRecordImpl<UsersRecord>(Users.USERS_) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var name: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var email: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised UsersRecord
     */
    constructor(id: UUID? = null, name: String, email: String): this() {
        this.id = id
        this.name = name
        this.email = email
        resetTouchedOnNotNull()
    }
}
