@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package rosemary_and_thyme.backend.models.`public`.tables.references




/**
 * The table <code>public.hero_images</code>.
 */
val HERO_IMAGES: rosemary_and_thyme.backend.models.`public`.tables.HeroImages = rosemary_and_thyme.backend.models.`public`.tables.HeroImages.HERO_IMAGES

/**
 * The table <code>public.ingredients</code>.
 */
val INGREDIENTS: rosemary_and_thyme.backend.models.`public`.tables.Ingredients = rosemary_and_thyme.backend.models.`public`.tables.Ingredients.INGREDIENTS

/**
 * The table <code>public.instruction_images</code>.
 */
val INSTRUCTION_IMAGES: rosemary_and_thyme.backend.models.`public`.tables.InstructionImages = rosemary_and_thyme.backend.models.`public`.tables.InstructionImages.INSTRUCTION_IMAGES

/**
 * The table <code>public.instructions</code>.
 */
val INSTRUCTIONS: rosemary_and_thyme.backend.models.`public`.tables.Instructions = rosemary_and_thyme.backend.models.`public`.tables.Instructions.INSTRUCTIONS

/**
 * The table <code>public.recipes</code>.
 */
val RECIPES: rosemary_and_thyme.backend.models.`public`.tables.Recipes = rosemary_and_thyme.backend.models.`public`.tables.Recipes.RECIPES

/**
 * The table <code>public.users</code>.
 */
val USERS: rosemary_and_thyme.backend.models.`public`.tables.Users = rosemary_and_thyme.backend.models.`public`.tables.Users.USERS
