/*
 * This file is generated by jOOQ.
 */
package rosemary_and_thyme.backend.models.`public`.tables


import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Instructions(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord>?,
    parentPath: InverseForeignKey<out Record, rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord>?,
    aliased: Table<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord>(
    alias,
    rosemary_and_thyme.backend.models.`public`.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.instructions</code>
         */
        val INSTRUCTIONS: Instructions = Instructions()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord> = rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord::class.java

    /**
     * The column <code>public.instructions.id</code>.
     */
    val ID: TableField<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.instructions.index</code>.
     */
    val INDEX: TableField<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord, Int?> = createField(DSL.name("index"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.instructions.instruction</code>.
     */
    val INSTRUCTION: TableField<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord, String?> = createField(DSL.name("instruction"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.instructions.recipe_id</code>.
     */
    val RECIPE_ID: TableField<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord, UUID?> = createField(DSL.name("recipe_id"), SQLDataType.UUID.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.instructions</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.instructions</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.instructions</code> table reference
     */
    constructor(): this(DSL.name("instructions"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord>?, parentPath: InverseForeignKey<out Record, rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, INSTRUCTIONS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class InstructionsPath : Instructions, Path<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord>?, parentPath: InverseForeignKey<out Record, rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord>): super(alias, aliased)
        override fun `as`(alias: String): InstructionsPath = InstructionsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): InstructionsPath = InstructionsPath(alias, this)
        override fun `as`(alias: Table<*>): InstructionsPath = InstructionsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else rosemary_and_thyme.backend.models.`public`.Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord> = rosemary_and_thyme.backend.models.`public`.keys.INSTRUCTIONS_PKEY
    override fun getUniqueKeys(): List<UniqueKey<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord>> = listOf(rosemary_and_thyme.backend.models.`public`.keys.INSTRUCTIONS_RECIPE_ID_INDEX_KEY)
    override fun getReferences(): List<ForeignKey<rosemary_and_thyme.backend.models.`public`.tables.records.InstructionsRecord, *>> = listOf(rosemary_and_thyme.backend.models.`public`.keys.INSTRUCTIONS__INSTRUCTIONS_RECIPE_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.recipes</code> table.
     */
    fun recipes(): rosemary_and_thyme.backend.models.`public`.tables.Recipes.RecipesPath = recipes
    val recipes: rosemary_and_thyme.backend.models.`public`.tables.Recipes.RecipesPath by lazy { rosemary_and_thyme.backend.models.`public`.tables.Recipes.RecipesPath(this, rosemary_and_thyme.backend.models.`public`.keys.INSTRUCTIONS__INSTRUCTIONS_RECIPE_ID_FKEY, null) }

    private lateinit var _instructionImages: rosemary_and_thyme.backend.models.`public`.tables.InstructionImages.InstructionImagesPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.instruction_images</code> table
     */
    fun instructionImages(): rosemary_and_thyme.backend.models.`public`.tables.InstructionImages.InstructionImagesPath {
        if (!this::_instructionImages.isInitialized)
            _instructionImages = rosemary_and_thyme.backend.models.`public`.tables.InstructionImages.InstructionImagesPath(this, null, rosemary_and_thyme.backend.models.`public`.keys.INSTRUCTION_IMAGES__INSTRUCTION_IMAGES_INSTRUCTION_ID_FKEY.inverseKey)

        return _instructionImages;
    }

    val instructionImages: rosemary_and_thyme.backend.models.`public`.tables.InstructionImages.InstructionImagesPath
        get(): rosemary_and_thyme.backend.models.`public`.tables.InstructionImages.InstructionImagesPath = instructionImages()
    override fun `as`(alias: String): Instructions = Instructions(DSL.name(alias), this)
    override fun `as`(alias: Name): Instructions = Instructions(alias, this)
    override fun `as`(alias: Table<*>): Instructions = Instructions(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Instructions = Instructions(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Instructions = Instructions(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Instructions = Instructions(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Instructions = Instructions(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Instructions = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Instructions = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Instructions = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Instructions = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Instructions = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Instructions = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Instructions = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): Instructions = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): Instructions = where(DSL.notExists(select))
}
