/*
 * This file is generated by jOOQ.
 */
package rosemary_and_thyme.backend.models.`public`.tables


import java.time.LocalDate
import java.util.UUID

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Recipes(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord>?,
    parentPath: InverseForeignKey<out Record, rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord>?,
    aliased: Table<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord>(
    alias,
    rosemary_and_thyme.backend.models.`public`.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.recipes</code>
         */
        val RECIPES: Recipes = Recipes()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord> = rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord::class.java

    /**
     * The column <code>public.recipes.id</code>.
     */
    val ID: TableField<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.recipes.name</code>.
     */
    val NAME: TableField<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord, String?> = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.recipes.description</code>.
     */
    val DESCRIPTION: TableField<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord, String?> = createField(DSL.name("description"), SQLDataType.VARCHAR.nullable(false), this, "")

    /**
     * The column <code>public.recipes.cook_time</code>.
     */
    val COOK_TIME: TableField<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord, String?> = createField(DSL.name("cook_time"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.recipes.side_notes</code>.
     */
    val SIDE_NOTES: TableField<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord, String?> = createField(DSL.name("side_notes"), SQLDataType.VARCHAR, this, "")

    /**
     * The column <code>public.recipes.difficulty</code>.
     */
    val DIFFICULTY: TableField<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord, Int?> = createField(DSL.name("difficulty"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.recipes.portions</code>.
     */
    val PORTIONS: TableField<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord, Int?> = createField(DSL.name("portions"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.recipes.likes</code>.
     */
    val LIKES: TableField<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord, Long?> = createField(DSL.name("likes"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "")

    /**
     * The column <code>public.recipes.created_date</code>.
     */
    val CREATED_DATE: TableField<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord, LocalDate?> = createField(DSL.name("created_date"), SQLDataType.LOCALDATE.nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_DATE"), SQLDataType.LOCALDATE)), this, "")

    /**
     * The column <code>public.recipes.user_id</code>.
     */
    val USER_ID: TableField<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord, UUID?> = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.recipes.user_name</code>.
     */
    val USER_NAME: TableField<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord, String?> = createField(DSL.name("user_name"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.recipes</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.recipes</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.recipes</code> table reference
     */
    constructor(): this(DSL.name("recipes"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord>?, parentPath: InverseForeignKey<out Record, rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, RECIPES, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class RecipesPath : Recipes, Path<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord>?, parentPath: InverseForeignKey<out Record, rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord>): super(alias, aliased)
        override fun `as`(alias: String): RecipesPath = RecipesPath(DSL.name(alias), this)
        override fun `as`(alias: Name): RecipesPath = RecipesPath(alias, this)
        override fun `as`(alias: Table<*>): RecipesPath = RecipesPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else rosemary_and_thyme.backend.models.`public`.Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<rosemary_and_thyme.backend.models.`public`.tables.records.RecipesRecord> = rosemary_and_thyme.backend.models.`public`.keys.RECIPES_PKEY

    private lateinit var _heroImages: rosemary_and_thyme.backend.models.`public`.tables.HeroImages.HeroImagesPath

    /**
     * Get the implicit to-many join path to the <code>public.hero_images</code>
     * table
     */
    fun heroImages(): rosemary_and_thyme.backend.models.`public`.tables.HeroImages.HeroImagesPath {
        if (!this::_heroImages.isInitialized)
            _heroImages = rosemary_and_thyme.backend.models.`public`.tables.HeroImages.HeroImagesPath(this, null, rosemary_and_thyme.backend.models.`public`.keys.HERO_IMAGES__HERO_IMAGES_RECIPE_ID_FKEY.inverseKey)

        return _heroImages;
    }

    val heroImages: rosemary_and_thyme.backend.models.`public`.tables.HeroImages.HeroImagesPath
        get(): rosemary_and_thyme.backend.models.`public`.tables.HeroImages.HeroImagesPath = heroImages()

    private lateinit var _ingredients: rosemary_and_thyme.backend.models.`public`.tables.Ingredients.IngredientsPath

    /**
     * Get the implicit to-many join path to the <code>public.ingredients</code>
     * table
     */
    fun ingredients(): rosemary_and_thyme.backend.models.`public`.tables.Ingredients.IngredientsPath {
        if (!this::_ingredients.isInitialized)
            _ingredients = rosemary_and_thyme.backend.models.`public`.tables.Ingredients.IngredientsPath(this, null, rosemary_and_thyme.backend.models.`public`.keys.INGREDIENTS__INGREDIENTS_RECIPE_ID_FKEY.inverseKey)

        return _ingredients;
    }

    val ingredients: rosemary_and_thyme.backend.models.`public`.tables.Ingredients.IngredientsPath
        get(): rosemary_and_thyme.backend.models.`public`.tables.Ingredients.IngredientsPath = ingredients()

    private lateinit var _instructions: rosemary_and_thyme.backend.models.`public`.tables.Instructions.InstructionsPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.instructions</code> table
     */
    fun instructions(): rosemary_and_thyme.backend.models.`public`.tables.Instructions.InstructionsPath {
        if (!this::_instructions.isInitialized)
            _instructions = rosemary_and_thyme.backend.models.`public`.tables.Instructions.InstructionsPath(this, null, rosemary_and_thyme.backend.models.`public`.keys.INSTRUCTIONS__INSTRUCTIONS_RECIPE_ID_FKEY.inverseKey)

        return _instructions;
    }

    val instructions: rosemary_and_thyme.backend.models.`public`.tables.Instructions.InstructionsPath
        get(): rosemary_and_thyme.backend.models.`public`.tables.Instructions.InstructionsPath = instructions()
    override fun `as`(alias: String): Recipes = Recipes(DSL.name(alias), this)
    override fun `as`(alias: Name): Recipes = Recipes(alias, this)
    override fun `as`(alias: Table<*>): Recipes = Recipes(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Recipes = Recipes(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Recipes = Recipes(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Recipes = Recipes(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Recipes = Recipes(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Recipes = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Recipes = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Recipes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Recipes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Recipes = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Recipes = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Recipes = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): Recipes = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): Recipes = where(DSL.notExists(select))
}
