/*
 * This file is generated by jOOQ.
 */
package rosemary_and_thyme.backend.models


import kotlin.collections.List

import org.jooq.Constants
import org.jooq.Schema
import org.jooq.impl.CatalogImpl

import rosemary_and_thyme.backend.models.users.Users


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class DefaultCatalog : CatalogImpl("") {
    companion object {

        /**
         * The reference instance of <code>DEFAULT_CATALOG</code>
         */
        val DEFAULT_CATALOG: DefaultCatalog = DefaultCatalog()
    }

    /**
     * standard public schema
     */
    val PUBLIC: rosemary_and_thyme.backend.models.`public`.Public get(): rosemary_and_thyme.backend.models.`public`.Public = rosemary_and_thyme.backend.models.`public`.Public.PUBLIC

    /**
     * The schema <code>users</code>.
     */
    val USERS: Users get(): Users = Users.USERS

    override fun getSchemas(): List<Schema> = listOf(
        rosemary_and_thyme.backend.models.`public`.Public.PUBLIC,
        Users.USERS
    )

    /**
     * A reference to the 3.21 minor release of the code generator. If this
     * doesn't compile, it's because the runtime library uses an older minor
     * release, namely: 3.21. You can turn off the generation of this reference
     * by specifying /configuration/generator/generate/jooqVersionReference
     */
    private val REQUIRE_RUNTIME_JOOQ_VERSION = Constants.VERSION_3_21
}
