/*
 * This file is generated by jOOQ.
 */
package rosemary_and_thyme.backend.models.`public`.tables.records


import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class HeroImagesRecord private constructor() : UpdatableRecordImpl<HeroImagesRecord>(rosemary_and_thyme.backend.models.`public`.tables.HeroImages.HERO_IMAGES) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var index: Int
        set(value): Unit = set(1, value)
        get(): Int = get(1) as Int

    open var url: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var recipeId: UUID
        set(value): Unit = set(3, value)
        get(): UUID = get(3) as UUID

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised HeroImagesRecord
     */
    constructor(id: UUID? = null, index: Int, url: String, recipeId: UUID): this() {
        this.id = id
        this.index = index
        this.url = url
        this.recipeId = recipeId
        resetTouchedOnNotNull()
    }
}
