/*
 * This file is generated by jOOQ.
 */
package rosemary_and_thyme.backend.models.`public`.tables.records


import java.math.BigDecimal
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class IngredientsRecord private constructor() : UpdatableRecordImpl<IngredientsRecord>(rosemary_and_thyme.backend.models.`public`.tables.Ingredients.INGREDIENTS) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var name: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var index: Int
        set(value): Unit = set(2, value)
        get(): Int = get(2) as Int

    open var amount: BigDecimal
        set(value): Unit = set(3, value)
        get(): BigDecimal = get(3) as BigDecimal

    open var measuringUnit: String
        set(value): Unit = set(4, value)
        get(): String = get(4) as String

    open var recipeId: UUID
        set(value): Unit = set(5, value)
        get(): UUID = get(5) as UUID

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised IngredientsRecord
     */
    constructor(id: UUID? = null, name: String, index: Int, amount: BigDecimal, measuringUnit: String, recipeId: UUID): this() {
        this.id = id
        this.name = name
        this.index = index
        this.amount = amount
        this.measuringUnit = measuringUnit
        this.recipeId = recipeId
        resetTouchedOnNotNull()
    }
}
