/*
 * This file is generated by jOOQ.
 */
package rosemary_and_thyme.backend.models.`public`.tables.records


import java.time.LocalDate
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class RecipesRecord private constructor() : UpdatableRecordImpl<RecipesRecord>(rosemary_and_thyme.backend.models.`public`.tables.Recipes.RECIPES) {

    open var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open var name: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open var description: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open var cookTime: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open var sideNotes: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var difficulty: Int
        set(value): Unit = set(5, value)
        get(): Int = get(5) as Int

    open var portions: Int
        set(value): Unit = set(6, value)
        get(): Int = get(6) as Int

    open var likes: Long?
        set(value): Unit = set(7, value)
        get(): Long? = get(7) as Long?

    open var createdDate: LocalDate?
        set(value): Unit = set(8, value)
        get(): LocalDate? = get(8) as LocalDate?

    open var userId: UUID
        set(value): Unit = set(9, value)
        get(): UUID = get(9) as UUID

    open var userName: String
        set(value): Unit = set(10, value)
        get(): String = get(10) as String

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    /**
     * Create a detached, initialised RecipesRecord
     */
    constructor(id: UUID? = null, name: String, description: String, cookTime: String, sideNotes: String? = null, difficulty: Int, portions: Int, likes: Long? = null, createdDate: LocalDate? = null, userId: UUID, userName: String): this() {
        this.id = id
        this.name = name
        this.description = description
        this.cookTime = cookTime
        this.sideNotes = sideNotes
        this.difficulty = difficulty
        this.portions = portions
        this.likes = likes
        this.createdDate = createdDate
        this.userId = userId
        this.userName = userName
        resetTouchedOnNotNull()
    }
}
