@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package rosemary_and_thyme.backend.models.users.keys


import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal

import rosemary_and_thyme.backend.models.users.tables.Users
import rosemary_and_thyme.backend.models.users.tables.records.UsersRecord



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val USERS_PKEY: UniqueKey<UsersRecord> = Internal.createUniqueKey(Users.USERS_, DSL.name("users_pkey"), arrayOf(Users.USERS_.ID), true)
